name: Bug Report
description: Iets is kapot gegaan.
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Wat is er fout gegaan?
      description: Wat is er onverwachts gebeurd? (Geen detail is te klein!)
      placeholder: |
        > Beschrijf het probleem hier...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Wat had je verwacht?
      description: Wat had je verwacht? (Geen detail is te klein!)
      placeholder: |
        > Beschrijf het verwachte gedrag hier...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Hoe kunnen we het opnieuw laten gebeuren?
      description: Loop ons door de stappen om het probleem te reproduceren.
      placeholder: |
        1. Ga naar '...'
        2. Klik op '...'
        3. Let op de chaos
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Heb je extra context / informatie?
      description: Geef zoveel mogelijk informatie met betrekking tot het probleem.
      render: shell
      placeholder: |
        > Plak screenshots, console errors, etc.