name: Refactor Request
description: Hungry for spaghetti? Let’s cook.
title: "[Refactor]: "
labels:
  - refactor
  - triage
body:
  - type: textarea
    id: area
    attributes:
      label: Where’s the spaghetti?
      description: Which part of the codebase needs a little love?
      placeholder: |
        > e.g., src/components/Button.tsx
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why tidy up?
      description: What’s bugging you about this code?
      placeholder: |
        > e.g., Hard to read, logic too nested.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: When will it feel clean?
      description: What does “done” look like?
      placeholder: |
        > e.g., Code is a breeze to read, tests pass, everyone’s happy
    validations:
      required: true